export const iconNames = [
  'a2z',
  'arrowButton',
  'closepanel',
  'drag',
  'dragDark',
  'exit',
  'hamburger-menu',
  'hamburger-menuDark',
  'home',
  'homeDark',
  'list',
  'listDark',
  'logout',
  'magnifying',
  'magnifyingDark',
  'moon',
  'openpanel',
  'pencil',
  'pencilDark',
  'plus',
  'plusDark',
  'sun',
  'three-dots',
  'three-dotsDark',
  'trash',
  'trashDark',
  'user',
  'userDark',
  'x-button',
  'x-buttonDark',
  'z2a',
] as const;

export type IconName = (typeof iconNames)[number];
