const {
  MODE: ENVIRONMENT,
  VITE_API_URL: API_URL,
  VITE_AUTH0_DOMAIN: AUTH0_DOMAIN,
  VITE_AUTH0_CLIENT_ID: AUTH0_CLIENT_ID,
  VITE_AUTH0_AUDIENCE: AUTH0_AUDIENCE,
  VITE_IS_AUTH0_DISABLED: IS_AUTH0_DISABLED,
  VITE_MOCK_USER_ID: MOCK_USER_ID,
} = import.meta.env;

export {
  ENVIRONMENT,
  API_URL,
  AUTH0_DOMAIN,
  AUTH0_CLIENT_ID,
  AUTH0_AUDIENCE,
  IS_AUTH0_DISABLED,
  MOCK_USER_ID,
};
