version: "3.9"

services:
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.development
    environment:
      - USE_MOCK=true
    depends_on:
      - redis
    command: sh -c "node dist/mocks/populateRedis.js && yarn dev"

  client:
    build:
      context: ./client
      args:
        VITE_MODE: development
        VITE_USE_MOCK: true
    container_name: client
    ports:
      - "3001:4173"
    env_file:
      - ./client/.env.development
    environment:
      - VITE_MODE=development
      - VITE_USE_MOCK=true
    depends_on:
      - backend

volumes:
  redis-data:
