version: "3.9"

services:
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=taskmaster
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: ${NODE_ENV:-development}
        DB_TYPE: ${DB_TYPE:-mongo}
        IS_AUTH0_DISABLED: ${IS_AUTH0_DISABLED:-true}
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.development
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - IS_AUTH0_DISABLED=${IS_AUTH0_DISABLED:-true}
      - DB_TYPE=${DB_TYPE:-mongo}
      - MONGODB_URI=mongodb://mongodb:27017/taskmaster
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    command: >
      sh -c "
        if [ \"$$DB_TYPE\" = \"mongo\" ]; then
          node dist/mocks/populateMongo.js
        else
          node dist/mocks/populateRedis.js
        fi
        exec yarn start
      "

  client:
    build:
      context: ./client
      args:
        VITE_MODE: development
        VITE_MOCK_USER_ID: ${VITE_MOCK_USER_ID:-mock-user-id}
        VITE_IS_AUTH0_DISABLED: true
    container_name: client
    ports:
      - "3001:4173"
    env_file:
      - ./client/.env.development
    environment:
      - VITE_MODE=${NODE_ENV:-staging}
      - VITE_IS_AUTH0_DISABLED=${USE_MOCK:-true}
      - VITE_MOCK_USER_ID=${VITE_MOCK_USER_ID:-mock-user-id}
    depends_on:
      backend:
        condition: service_healthy
    restart: always

volumes:
  redis-data:
  mongodb-data:
